services:
  database:
    image: mysql:8.4
    container_name: cesizen-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER:-cesizen} -p${MYSQL_PASSWORD:-cesizen} --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - database_data:/var/lib/mysql

    ports:
      - "3306:3306"


  api:
    build:
      context: ./cesizen-api
      dockerfile: Dockerfile

    container_name: cesizen-api
    restart: unless-stopped

    depends_on:
      database:
        condition: service_healthy

    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.4&charset=utf8mb4"
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      DEFAULT_URI: ${DEFAULT_URI}
      APP_RUNTIME_OPTIONS: '{"disable_dotenv":true}'

    ports:
      - "8000:8000"


  frontweb:
    build:
      context: ./cesizen-frontweb
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}

    container_name: cesizen-frontweb
    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    environment:
      API_URL: ${API_URL}

    ports:
      - "3000:3000"


volumes:
  database_data: