services:
  database:
    image: mysql:8.4
    container_name: cesizen-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER:-cesizen} -p${MYSQL_PASSWORD:-cesizen} --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - database_data:/var/lib/mysql

    ports:
      - "3306:3306"


  api:
    build:
      context: ./cesizen-api
      dockerfile: Dockerfile

    container_name: cesizen-api
    restart: unless-stopped

    depends_on:
      database:
        condition: service_healthy

    env_file:
      - ./cesizen-api/.env.docker

    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-cesizen}:${MYSQL_PASSWORD:-cesizen}@database:3306/${MYSQL_DATABASE:-cesizen}?serverVersion=8.4&charset=utf8mb4"

    ports:
      - "8000:8000"


  frontweb:
    build:
      context: ./cesizen-frontweb
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}

    container_name: cesizen-frontweb
    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    env_file:
      - ./cesizen-frontweb/.env.docker

    environment:
      API_URL: ${API_URL}

    ports:
      - "3000:3000"


volumes:
  database_data: