sonar.projectKey=arnaudvlb_cesizen
sonar.organization=arnaudvlb

sonar.sources=cesizen-api/src,cesizen-frontweb
sonar.tests=cesizen-api/tests

sonar.exclusions=**/node_modules/**,**/.next/**,**/vendor/**,cesizen-mobile/**

sonar.sourceEncoding=UTF-8