# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        stateless_token_ids:
            - submit
        check_header: true
        cookie_name: csrf-token

    session: true
    
    assets: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
