security:
    password_hashers:
        App\Entity\Utilisateurs: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }